/* 
 * Selling Partner API for Reports
 *
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * OpenAPI spec version: 2021-06-30
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.Reports;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Reports.Test
{
    /// <summary>
    ///  Class for testing ReportScheduleList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReportScheduleListTests
    {
        // TODO uncomment below to declare an instance variable for ReportScheduleList
        //private ReportScheduleList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReportScheduleList
            //instance = new ReportScheduleList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReportScheduleList
        /// </summary>
        [Test]
        public void ReportScheduleListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReportScheduleList
            //Assert.IsInstanceOfType<ReportScheduleList> (instance, "variable 'instance' is a ReportScheduleList");
        }


        /// <summary>
        /// Test the property 'ReportSchedules'
        /// </summary>
        [Test]
        public void ReportSchedulesTest()
        {
            // TODO unit test for the property 'ReportSchedules'
        }

    }

}
