/* 
 * Selling Partner API for Reports
 *
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * OpenAPI spec version: 2021-06-30
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.Reports;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Reports.Test
{
    /// <summary>
    ///  Class for testing ReportSchedule
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReportScheduleTests
    {
        // TODO uncomment below to declare an instance variable for ReportSchedule
        //private ReportSchedule instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReportSchedule
            //instance = new ReportSchedule();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReportSchedule
        /// </summary>
        [Test]
        public void ReportScheduleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReportSchedule
            //Assert.IsInstanceOfType<ReportSchedule> (instance, "variable 'instance' is a ReportSchedule");
        }


        /// <summary>
        /// Test the property 'ReportScheduleId'
        /// </summary>
        [Test]
        public void ReportScheduleIdTest()
        {
            // TODO unit test for the property 'ReportScheduleId'
        }
        /// <summary>
        /// Test the property 'ReportType'
        /// </summary>
        [Test]
        public void ReportTypeTest()
        {
            // TODO unit test for the property 'ReportType'
        }
        /// <summary>
        /// Test the property 'MarketplaceIds'
        /// </summary>
        [Test]
        public void MarketplaceIdsTest()
        {
            // TODO unit test for the property 'MarketplaceIds'
        }
        /// <summary>
        /// Test the property 'ReportOptions'
        /// </summary>
        [Test]
        public void ReportOptionsTest()
        {
            // TODO unit test for the property 'ReportOptions'
        }
        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Test]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }
        /// <summary>
        /// Test the property 'NextReportCreationTime'
        /// </summary>
        [Test]
        public void NextReportCreationTimeTest()
        {
            // TODO unit test for the property 'NextReportCreationTime'
        }

    }

}
