/* 
 * Selling Partner API for Reports
 *
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * OpenAPI spec version: 2021-06-30
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Amazon.SellingPartnerAPIAA.Clients.Client.SwaggerDateConverter;

namespace Amazon.SellingPartnerAPIAA.Clients.Models.Reports
{
    /// <summary>
    /// Information required for the report document.
    /// </summary>
    [DataContract]
    public partial class ReportDocument :  IEquatable<ReportDocument>, IValidatableObject
    {
        /// <summary>
        /// If the report document contents have been compressed, the compression algorithm used is returned in this property and you must decompress the report when you download. Otherwise, you can download the report directly. Refer to [Step 2. Download the report](doc:reports-api-v2021-06-30-retrieve-a-report#step-2-download-the-report) in the use case guide, where sample code is provided.
        /// </summary>
        /// <value>If the report document contents have been compressed, the compression algorithm used is returned in this property and you must decompress the report when you download. Otherwise, you can download the report directly. Refer to [Step 2. Download the report](doc:reports-api-v2021-06-30-retrieve-a-report#step-2-download-the-report) in the use case guide, where sample code is provided.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CompressionAlgorithmEnum
        {
            
            /// <summary>
            /// Enum GZIP for value: GZIP
            /// </summary>
            [EnumMember(Value = "GZIP")]
            GZIP = 1
        }

        /// <summary>
        /// If the report document contents have been compressed, the compression algorithm used is returned in this property and you must decompress the report when you download. Otherwise, you can download the report directly. Refer to [Step 2. Download the report](doc:reports-api-v2021-06-30-retrieve-a-report#step-2-download-the-report) in the use case guide, where sample code is provided.
        /// </summary>
        /// <value>If the report document contents have been compressed, the compression algorithm used is returned in this property and you must decompress the report when you download. Otherwise, you can download the report directly. Refer to [Step 2. Download the report](doc:reports-api-v2021-06-30-retrieve-a-report#step-2-download-the-report) in the use case guide, where sample code is provided.</value>
        [DataMember(Name="compressionAlgorithm", EmitDefaultValue=false)]
        public CompressionAlgorithmEnum? CompressionAlgorithm { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReportDocument" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReportDocument() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReportDocument" /> class.
        /// </summary>
        /// <param name="reportDocumentId">The identifier for the report document. This identifier is unique only in combination with a seller ID. (required).</param>
        /// <param name="url">A presigned URL for the report document. If &#x60;compressionAlgorithm&#x60; is not returned, you can download the report directly from this URL. This URL expires after 5 minutes. (required).</param>
        /// <param name="compressionAlgorithm">If the report document contents have been compressed, the compression algorithm used is returned in this property and you must decompress the report when you download. Otherwise, you can download the report directly. Refer to [Step 2. Download the report](doc:reports-api-v2021-06-30-retrieve-a-report#step-2-download-the-report) in the use case guide, where sample code is provided..</param>
        public ReportDocument(string reportDocumentId = default(string), string url = default(string), CompressionAlgorithmEnum? compressionAlgorithm = default(CompressionAlgorithmEnum?))
        {
            // to ensure "reportDocumentId" is required (not null)
            if (reportDocumentId == null)
            {
                throw new InvalidDataException("reportDocumentId is a required property for ReportDocument and cannot be null");
            }
            else
            {
                this.ReportDocumentId = reportDocumentId;
            }
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new InvalidDataException("url is a required property for ReportDocument and cannot be null");
            }
            else
            {
                this.Url = url;
            }
            this.CompressionAlgorithm = compressionAlgorithm;
        }
        
        /// <summary>
        /// The identifier for the report document. This identifier is unique only in combination with a seller ID.
        /// </summary>
        /// <value>The identifier for the report document. This identifier is unique only in combination with a seller ID.</value>
        [DataMember(Name="reportDocumentId", EmitDefaultValue=false)]
        public string ReportDocumentId { get; set; }

        /// <summary>
        /// A presigned URL for the report document. If &#x60;compressionAlgorithm&#x60; is not returned, you can download the report directly from this URL. This URL expires after 5 minutes.
        /// </summary>
        /// <value>A presigned URL for the report document. If &#x60;compressionAlgorithm&#x60; is not returned, you can download the report directly from this URL. This URL expires after 5 minutes.</value>
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ReportDocument {\n");
            sb.Append("  ReportDocumentId: ").Append(ReportDocumentId).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  CompressionAlgorithm: ").Append(CompressionAlgorithm).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReportDocument);
        }

        /// <summary>
        /// Returns true if ReportDocument instances are equal
        /// </summary>
        /// <param name="input">Instance of ReportDocument to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReportDocument input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ReportDocumentId == input.ReportDocumentId ||
                    (this.ReportDocumentId != null &&
                    this.ReportDocumentId.Equals(input.ReportDocumentId))
                ) && 
                (
                    this.Url == input.Url ||
                    (this.Url != null &&
                    this.Url.Equals(input.Url))
                ) && 
                (
                    this.CompressionAlgorithm == input.CompressionAlgorithm ||
                    (this.CompressionAlgorithm != null &&
                    this.CompressionAlgorithm.Equals(input.CompressionAlgorithm))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ReportDocumentId != null)
                    hashCode = hashCode * 59 + this.ReportDocumentId.GetHashCode();
                if (this.Url != null)
                    hashCode = hashCode * 59 + this.Url.GetHashCode();
                if (this.CompressionAlgorithm != null)
                    hashCode = hashCode * 59 + this.CompressionAlgorithm.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
