/* 
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Amazon.SellingPartnerAPIAA.Client.Client;
using Amazon.SellingPartnerAPIAA.Client.Api;
using Amazon.SellingPartnerAPIAA.Client.Model;

namespace Amazon.SellingPartnerAPIAA.Client.Test
{
    /// <summary>
    ///  Class for testing ApprovalsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ApprovalsApiTests
    {
        private ApprovalsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to initialize instance for testing
            //instance = new ApprovalsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ApprovalsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ApprovalsApi
            //Assert.IsInstanceOfType(typeof(ApprovalsApi), instance, "instance is a ApprovalsApi");
        }

        
        /// <summary>
        /// Test GetOrderItemsApprovals
        /// </summary>
        [Test]
        public void GetOrderItemsApprovalsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orderId = null;
            //string nextToken = null;
            //List<ItemApprovalType> itemApprovalTypes = null;
            //List<ItemApprovalStatus> itemApprovalStatus = null;
            //var response = instance.GetOrderItemsApprovals(orderId, nextToken, itemApprovalTypes, itemApprovalStatus);
            //Assert.IsInstanceOf<GetOrderApprovalsResponse> (response, "response is GetOrderApprovalsResponse");
        }
        
        /// <summary>
        /// Test UpdateOrderItemsApprovals
        /// </summary>
        [Test]
        public void UpdateOrderItemsApprovalsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string orderId = null;
            //UpdateOrderApprovalsRequest payload = null;
            //instance.UpdateOrderItemsApprovals(orderId, payload);
            
        }
        
    }

}
