/* 
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.Pricing;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Pricing.Test
{
    /// <summary>
    ///  Class for testing OfferCountType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OfferCountTypeTests
    {
        // TODO uncomment below to declare an instance variable for OfferCountType
        //private OfferCountType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OfferCountType
            //instance = new OfferCountType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OfferCountType
        /// </summary>
        [Test]
        public void OfferCountTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OfferCountType
            //Assert.IsInstanceOfType<OfferCountType> (instance, "variable 'instance' is a OfferCountType");
        }


        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Test]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }
        /// <summary>
        /// Test the property 'FulfillmentChannel'
        /// </summary>
        [Test]
        public void FulfillmentChannelTest()
        {
            // TODO unit test for the property 'FulfillmentChannel'
        }
        /// <summary>
        /// Test the property 'OfferCount'
        /// </summary>
        [Test]
        public void OfferCountTest()
        {
            // TODO unit test for the property 'OfferCount'
        }

    }

}
