/* 
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.Pricing;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Pricing.Test
{
    /// <summary>
    ///  Class for testing Points
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PointsTests
    {
        // TODO uncomment below to declare an instance variable for Points
        //private Points instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Points
            //instance = new Points();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Points
        /// </summary>
        [Test]
        public void PointsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Points
            //Assert.IsInstanceOfType<Points> (instance, "variable 'instance' is a Points");
        }


        /// <summary>
        /// Test the property 'PointsNumber'
        /// </summary>
        [Test]
        public void PointsNumberTest()
        {
            // TODO unit test for the property 'PointsNumber'
        }
        /// <summary>
        /// Test the property 'PointsMonetaryValue'
        /// </summary>
        [Test]
        public void PointsMonetaryValueTest()
        {
            // TODO unit test for the property 'PointsMonetaryValue'
        }

    }

}
