/* 
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.Orders;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Orders.Test
{
    /// <summary>
    ///  Class for testing AutomatedShippingSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AutomatedShippingSettingsTests
    {
        // TODO uncomment below to declare an instance variable for AutomatedShippingSettings
        //private AutomatedShippingSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AutomatedShippingSettings
            //instance = new AutomatedShippingSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AutomatedShippingSettings
        /// </summary>
        [Test]
        public void AutomatedShippingSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AutomatedShippingSettings
            //Assert.IsInstanceOfType<AutomatedShippingSettings> (instance, "variable 'instance' is a AutomatedShippingSettings");
        }


        /// <summary>
        /// Test the property 'HasAutomatedShippingSettings'
        /// </summary>
        [Test]
        public void HasAutomatedShippingSettingsTest()
        {
            // TODO unit test for the property 'HasAutomatedShippingSettings'
        }
        /// <summary>
        /// Test the property 'AutomatedCarrier'
        /// </summary>
        [Test]
        public void AutomatedCarrierTest()
        {
            // TODO unit test for the property 'AutomatedCarrier'
        }
        /// <summary>
        /// Test the property 'AutomatedShipMethod'
        /// </summary>
        [Test]
        public void AutomatedShipMethodTest()
        {
            // TODO unit test for the property 'AutomatedShipMethod'
        }

    }

}
