/* 
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.Orders;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing OtherDeliveryAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OtherDeliveryAttributesTests
    {
        // TODO uncomment below to declare an instance variable for OtherDeliveryAttributes
        //private OtherDeliveryAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OtherDeliveryAttributes
            //instance = new OtherDeliveryAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OtherDeliveryAttributes
        /// </summary>
        [Test]
        public void OtherDeliveryAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OtherDeliveryAttributes
            //Assert.IsInstanceOfType<OtherDeliveryAttributes> (instance, "variable 'instance' is a OtherDeliveryAttributes");
        }



    }

}
