/* 
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.Orders;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Test
{
    /// <summary>
    ///  Class for testing PreferredDeliveryTime
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PreferredDeliveryTimeTests
    {
        // TODO uncomment below to declare an instance variable for PreferredDeliveryTime
        //private PreferredDeliveryTime instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PreferredDeliveryTime
            //instance = new PreferredDeliveryTime();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PreferredDeliveryTime
        /// </summary>
        [Test]
        public void PreferredDeliveryTimeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PreferredDeliveryTime
            //Assert.IsInstanceOfType<PreferredDeliveryTime> (instance, "variable 'instance' is a PreferredDeliveryTime");
        }


        /// <summary>
        /// Test the property 'BusinessHours'
        /// </summary>
        [Test]
        public void BusinessHoursTest()
        {
            // TODO unit test for the property 'BusinessHours'
        }
        /// <summary>
        /// Test the property 'ExceptionDates'
        /// </summary>
        [Test]
        public void ExceptionDatesTest()
        {
            // TODO unit test for the property 'ExceptionDates'
        }

    }

}
