/* 
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.Orders;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Orders.Test
{
    /// <summary>
    ///  Class for testing RegulatedOrderVerificationStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RegulatedOrderVerificationStatusTests
    {
        // TODO uncomment below to declare an instance variable for RegulatedOrderVerificationStatus
        //private RegulatedOrderVerificationStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RegulatedOrderVerificationStatus
            //instance = new RegulatedOrderVerificationStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RegulatedOrderVerificationStatus
        /// </summary>
        [Test]
        public void RegulatedOrderVerificationStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RegulatedOrderVerificationStatus
            //Assert.IsInstanceOfType<RegulatedOrderVerificationStatus> (instance, "variable 'instance' is a RegulatedOrderVerificationStatus");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'RequiresMerchantAction'
        /// </summary>
        [Test]
        public void RequiresMerchantActionTest()
        {
            // TODO unit test for the property 'RequiresMerchantAction'
        }
        /// <summary>
        /// Test the property 'ValidRejectionReasons'
        /// </summary>
        [Test]
        public void ValidRejectionReasonsTest()
        {
            // TODO unit test for the property 'ValidRejectionReasons'
        }
        /// <summary>
        /// Test the property 'RejectionReason'
        /// </summary>
        [Test]
        public void RejectionReasonTest()
        {
            // TODO unit test for the property 'RejectionReason'
        }
        /// <summary>
        /// Test the property 'ReviewDate'
        /// </summary>
        [Test]
        public void ReviewDateTest()
        {
            // TODO unit test for the property 'ReviewDate'
        }
        /// <summary>
        /// Test the property 'ExternalReviewerId'
        /// </summary>
        [Test]
        public void ExternalReviewerIdTest()
        {
            // TODO unit test for the property 'ExternalReviewerId'
        }

    }

}
