/* 
 * Selling Partner API for Feeds
 *
 * The Selling Partner API for Feeds lets you upload data to Amazon on behalf of a selling partner.
 *
 * OpenAPI spec version: 2021-06-30
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Client.Api;
using Amazon.SellingPartnerAPIAA.Client.Model;
using Amazon.SellingPartnerAPIAA.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Client.Test
{
    /// <summary>
    ///  Class for testing CreateFeedSpecification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreateFeedSpecificationTests
    {
        // TODO uncomment below to declare an instance variable for CreateFeedSpecification
        //private CreateFeedSpecification instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateFeedSpecification
            //instance = new CreateFeedSpecification();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateFeedSpecification
        /// </summary>
        [Test]
        public void CreateFeedSpecificationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateFeedSpecification
            //Assert.IsInstanceOfType<CreateFeedSpecification> (instance, "variable 'instance' is a CreateFeedSpecification");
        }


        /// <summary>
        /// Test the property 'FeedType'
        /// </summary>
        [Test]
        public void FeedTypeTest()
        {
            // TODO unit test for the property 'FeedType'
        }
        /// <summary>
        /// Test the property 'MarketplaceIds'
        /// </summary>
        [Test]
        public void MarketplaceIdsTest()
        {
            // TODO unit test for the property 'MarketplaceIds'
        }
        /// <summary>
        /// Test the property 'InputFeedDocumentId'
        /// </summary>
        [Test]
        public void InputFeedDocumentIdTest()
        {
            // TODO unit test for the property 'InputFeedDocumentId'
        }
        /// <summary>
        /// Test the property 'FeedOptions'
        /// </summary>
        [Test]
        public void FeedOptionsTest()
        {
            // TODO unit test for the property 'FeedOptions'
        }

    }

}
