/* 
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Client.Api;
using Amazon.SellingPartnerAPIAA.Client.Model;
using Amazon.SellingPartnerAPIAA.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Client.Test
{
    /// <summary>
    ///  Class for testing ItemApproval
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ItemApprovalTests
    {
        // TODO uncomment below to declare an instance variable for ItemApproval
        //private ItemApproval instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ItemApproval
            //instance = new ItemApproval();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ItemApproval
        /// </summary>
        [Test]
        public void ItemApprovalInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ItemApproval
            //Assert.IsInstanceOfType<ItemApproval> (instance, "variable 'instance' is a ItemApproval");
        }


        /// <summary>
        /// Test the property 'SequenceId'
        /// </summary>
        [Test]
        public void SequenceIdTest()
        {
            // TODO unit test for the property 'SequenceId'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Actor'
        /// </summary>
        [Test]
        public void ActorTest()
        {
            // TODO unit test for the property 'Actor'
        }
        /// <summary>
        /// Test the property 'Approver'
        /// </summary>
        [Test]
        public void ApproverTest()
        {
            // TODO unit test for the property 'Approver'
        }
        /// <summary>
        /// Test the property 'ApprovalAction'
        /// </summary>
        [Test]
        public void ApprovalActionTest()
        {
            // TODO unit test for the property 'ApprovalAction'
        }
        /// <summary>
        /// Test the property 'ApprovalActionProcessStatus'
        /// </summary>
        [Test]
        public void ApprovalActionProcessStatusTest()
        {
            // TODO unit test for the property 'ApprovalActionProcessStatus'
        }
        /// <summary>
        /// Test the property 'ApprovalActionProcessStatusMessage'
        /// </summary>
        [Test]
        public void ApprovalActionProcessStatusMessageTest()
        {
            // TODO unit test for the property 'ApprovalActionProcessStatusMessage'
        }

    }

}
