/* 
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Client.Api;
using Amazon.SellingPartnerAPIAA.Client.Model;
using Amazon.SellingPartnerAPIAA.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Client.Test
{
    /// <summary>
    ///  Class for testing QuantityDiscountType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QuantityDiscountTypeTests
    {
        // TODO uncomment below to declare an instance variable for QuantityDiscountType
        //private QuantityDiscountType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QuantityDiscountType
            //instance = new QuantityDiscountType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QuantityDiscountType
        /// </summary>
        [Test]
        public void QuantityDiscountTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QuantityDiscountType
            //Assert.IsInstanceOfType<QuantityDiscountType> (instance, "variable 'instance' is a QuantityDiscountType");
        }



    }

}
