/* 
 * Selling Partner API for Pricing
 *
 * The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Client.Api;
using Amazon.SellingPartnerAPIAA.Client.Model;
using Amazon.SellingPartnerAPIAA.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Client.Test
{
    /// <summary>
    ///  Class for testing SalesRankType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SalesRankTypeTests
    {
        // TODO uncomment below to declare an instance variable for SalesRankType
        //private SalesRankType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SalesRankType
            //instance = new SalesRankType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SalesRankType
        /// </summary>
        [Test]
        public void SalesRankTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SalesRankType
            //Assert.IsInstanceOfType<SalesRankType> (instance, "variable 'instance' is a SalesRankType");
        }


        /// <summary>
        /// Test the property 'ProductCategoryId'
        /// </summary>
        [Test]
        public void ProductCategoryIdTest()
        {
            // TODO unit test for the property 'ProductCategoryId'
        }
        /// <summary>
        /// Test the property 'Rank'
        /// </summary>
        [Test]
        public void RankTest()
        {
            // TODO unit test for the property 'Rank'
        }

    }

}
