/* 
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ConfirmShipmentOrderItemsList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConfirmShipmentOrderItemsListTests
    {
        // TODO uncomment below to declare an instance variable for ConfirmShipmentOrderItemsList
        //private ConfirmShipmentOrderItemsList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConfirmShipmentOrderItemsList
            //instance = new ConfirmShipmentOrderItemsList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConfirmShipmentOrderItemsList
        /// </summary>
        [Test]
        public void ConfirmShipmentOrderItemsListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConfirmShipmentOrderItemsList
            //Assert.IsInstanceOfType<ConfirmShipmentOrderItemsList> (instance, "variable 'instance' is a ConfirmShipmentOrderItemsList");
        }



    }

}
