/* 
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ItemApprovalAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ItemApprovalActionTests
    {
        // TODO uncomment below to declare an instance variable for ItemApprovalAction
        //private ItemApprovalAction instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ItemApprovalAction
            //instance = new ItemApprovalAction();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ItemApprovalAction
        /// </summary>
        [Test]
        public void ItemApprovalActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ItemApprovalAction
            //Assert.IsInstanceOfType<ItemApprovalAction> (instance, "variable 'instance' is a ItemApprovalAction");
        }


        /// <summary>
        /// Test the property 'ActionType'
        /// </summary>
        [Test]
        public void ActionTypeTest()
        {
            // TODO unit test for the property 'ActionType'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Test]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }
        /// <summary>
        /// Test the property 'Changes'
        /// </summary>
        [Test]
        public void ChangesTest()
        {
            // TODO unit test for the property 'Changes'
        }

    }

}
