/* 
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OrderItemApprovals
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderItemApprovalsTests
    {
        // TODO uncomment below to declare an instance variable for OrderItemApprovals
        //private OrderItemApprovals instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderItemApprovals
            //instance = new OrderItemApprovals();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderItemApprovals
        /// </summary>
        [Test]
        public void OrderItemApprovalsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderItemApprovals
            //Assert.IsInstanceOfType<OrderItemApprovals> (instance, "variable 'instance' is a OrderItemApprovals");
        }


        /// <summary>
        /// Test the property 'OrderItemId'
        /// </summary>
        [Test]
        public void OrderItemIdTest()
        {
            // TODO unit test for the property 'OrderItemId'
        }
        /// <summary>
        /// Test the property 'ApprovalType'
        /// </summary>
        [Test]
        public void ApprovalTypeTest()
        {
            // TODO unit test for the property 'ApprovalType'
        }
        /// <summary>
        /// Test the property 'ApprovalStatus'
        /// </summary>
        [Test]
        public void ApprovalStatusTest()
        {
            // TODO unit test for the property 'ApprovalStatus'
        }
        /// <summary>
        /// Test the property 'ItemApprovals'
        /// </summary>
        [Test]
        public void ItemApprovalsTest()
        {
            // TODO unit test for the property 'ItemApprovals'
        }

    }

}
