/* 
 * Selling Partner API for Catalog Items
 *
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * OpenAPI spec version: 2022-04-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Amazon.SellingPartnerAPIAA.Clients.API;
using Amazon.SellingPartnerAPIAA.Clients.Models.Catalog;
using Amazon.SellingPartnerAPIAA.Clients.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Amazon.SellingPartnerAPIAA.Clients.Catalog.Test
{
    /// <summary>
    ///  Class for testing ItemBrowseClassification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ItemBrowseClassificationTests
    {
        // TODO uncomment below to declare an instance variable for ItemBrowseClassification
        //private ItemBrowseClassification instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ItemBrowseClassification
            //instance = new ItemBrowseClassification();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ItemBrowseClassification
        /// </summary>
        [Test]
        public void ItemBrowseClassificationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ItemBrowseClassification
            //Assert.IsInstanceOfType<ItemBrowseClassification> (instance, "variable 'instance' is a ItemBrowseClassification");
        }


        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'ClassificationId'
        /// </summary>
        [Test]
        public void ClassificationIdTest()
        {
            // TODO unit test for the property 'ClassificationId'
        }

    }

}
