/* 
 * Selling Partner API for Reports
 *
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * OpenAPI spec version: 2021-06-30
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Amazon.SellingPartnerAPIAA.Client.Client.SwaggerDateConverter;

namespace Amazon.SellingPartnerAPIAA.Client.Model
{
    /// <summary>
    /// Response schema.
    /// </summary>
    [DataContract]
    public partial class CreateReportScheduleResponse :  IEquatable<CreateReportScheduleResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateReportScheduleResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateReportScheduleResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateReportScheduleResponse" /> class.
        /// </summary>
        /// <param name="reportScheduleId">The identifier for the report schedule. This identifier is unique only in combination with a seller ID. (required).</param>
        public CreateReportScheduleResponse(string reportScheduleId = default(string))
        {
            // to ensure "reportScheduleId" is required (not null)
            if (reportScheduleId == null)
            {
                throw new InvalidDataException("reportScheduleId is a required property for CreateReportScheduleResponse and cannot be null");
            }
            else
            {
                this.ReportScheduleId = reportScheduleId;
            }
        }
        
        /// <summary>
        /// The identifier for the report schedule. This identifier is unique only in combination with a seller ID.
        /// </summary>
        /// <value>The identifier for the report schedule. This identifier is unique only in combination with a seller ID.</value>
        [DataMember(Name="reportScheduleId", EmitDefaultValue=false)]
        public string ReportScheduleId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateReportScheduleResponse {\n");
            sb.Append("  ReportScheduleId: ").Append(ReportScheduleId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateReportScheduleResponse);
        }

        /// <summary>
        /// Returns true if CreateReportScheduleResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateReportScheduleResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateReportScheduleResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ReportScheduleId == input.ReportScheduleId ||
                    (this.ReportScheduleId != null &&
                    this.ReportScheduleId.Equals(input.ReportScheduleId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ReportScheduleId != null)
                    hashCode = hashCode * 59 + this.ReportScheduleId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
